info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG

#spring:
#  cloud:
#    config:
#      uri: http://localhost:${config.port:8888}
#  config:
#    import: configserver:${spring.cloud.config.uri}


